name       : ekiga
version    : 4.0.1
release    : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/ekiga/4.0/ekiga-4.0.1.tar.xz : 5f4f491c9496cf65ba057a9345d6bb0278f4eca07bcda5baeecf50bfcd9a4a3b
license    : GPL-2.0
component  : network.im
summary    : Ekiga is an open source SoftPhone, Video Conferencing and Instant Messenger
    application.
description: |
    Ekiga is an open source SoftPhone, Video Conferencing and Instant Messenger application.
builddeps  :
    - pkgconfig(avahi-client)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gdk-2.0)
    - pkgconfig(gnome-icon-theme)
    - pkgconfig(libebook-1.2)
    - pkgconfig(libevent)
    - pkgconfig(libnotify)
    - pkgconfig(libsasl2)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libv4l1)
    - pkgconfig(opal)
    - pkgconfig(ptlib)
    - pkgconfig(rarian)
    - pkgconfig(sdl)
    - pkgconfig(xext)
    - pkgconfig(xv)
    - intltool
    - libboost-devel
setup      : |
    %reconfigure --disable-static --disable-gdu --disable-ldap --disable-scrollkeeper --enable-dbus --enable-avahi
build      : |
    %make
install    : |
    %make_install
